import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import slugify from 'slugify';

import connectDB from '@/config/database';
import Movie from '@/models/movie.model';
// import Genre from '@/models/genre.model';
// import Person from '@/models/person.model';

dotenv.config({ path: path.join(__dirname, '../../.env') });

const movies = [
  {
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    releaseDate: new Date('2010-07-16T00:00:00.000Z'),
    duration: 148,
    posterUrl: 'https://m.media-amazon.com/images/I/912AErFSBHL._AC_UF1000,1000_QL80_.jpg',
    backdropUrls: [
      'https://image.tmdb.org/t/p/original/s3TBrA1J7dCj4uBqXoWCMYUTL5A.jpg',
      'https://image.tmdb.org/t/p/original/4I22h244i4aLzS5gYn42aAd1Jry.jpg',
    ],
    trailerUrl: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
    status: 'RELEASED',
  },
  {
    title: 'The Dark Knight',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    releaseDate: new Date('2008-07-18T00:00:00.000Z'),
    duration: 152,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg',
    backdropUrls: [
      'https://image.tmdb.org/t/p/original/nMKdUUQBECcEBUACzQq1MM1r7vV.jpg',
      'https://image.tmdb.org/t/p/original/kk985i3i2g5B4a5s1F3b1aT2Hth.jpg',
    ],
    trailerUrl: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    status: 'RELEASED',
  },
  {
    title: 'Dune: Part Two',
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    releaseDate: new Date('2024-03-01T00:00:00.000Z'),
    duration: 166,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BNDNlNmViNWQtYTRhMi00ZDU2LThlZmYtZGQ2ZmI1NjA2MTJmXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_FMjpg_UX1000_.jpg',
    backdropUrls: [
      'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5TASgd.jpg',
      'https://image.tmdb.org/t/p/original/fypydCipcWDKDTTUFPYhRFcGOht.jpg',
    ],
    trailerUrl: 'https://www.youtube.com/watch?v=U2Qp5pL3ovA',
    status: 'NOW_SHOWING',
  },
  {
    title: 'Oppenheimer',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    releaseDate: new Date('2023-07-21T00:00:00.000Z'),
    duration: 180,
    posterUrl: 'https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_FMjpg_UX1000_.jpg',
    backdropUrls: ['https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg'],
    trailerUrl: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    status: 'NOW_SHOWING',
  },
];

const movies_v2 = [
    {
      title: 'Pulp Fiction',
      description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
      releaseDate: new Date('1994-10-14T00:00:00.000Z'),
      duration: 154,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2vyrB1.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/...4',
      videoUrl: 'https://www.youtube.com/embed/...4',
      status: 'RELEASED',
    },
    {
      title: 'Forrest Gump',
      description: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
      releaseDate: new Date('1994-07-06T00:00:00.000Z'),
      duration: 142,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/3h1JZGDhZ8Nz8KNrdlNYrx1SPAb.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/...5',
      videoUrl: 'https://www.youtube.com/embed/...5',
      status: 'RELEASED',
    },
    {
      title: 'The Shawshank Redemption',
      description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
      releaseDate: new Date('1994-09-23T00:00:00.000Z'),
      duration: 142,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/kXv9L61T2bQe1C9LpW2sM6m1t2I.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/...6',
      videoUrl: 'https://www.youtube.com/embed/...6',
      status: 'RELEASED',
    },
    {
      title: 'Spirited Away',
      description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
      releaseDate: new Date('2001-07-20T00:00:00.000Z'),
      duration: 125,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/mG3Qz5x3mbDkG62aM9S1dYJjSgD.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/...7',
      videoUrl: 'https://www.youtube.com/embed/...7',
      status: 'RELEASED',
    },
    {
      title: 'The Godfather',
      description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
      releaseDate: new Date('1972-03-24T00:00:00.000Z'),
      duration: 175,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/rSPw7VjmkTo2npHAbEK5_axG2u1.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/...8',
      videoUrl: 'https://www.youtube.com/embed/...8',
      status: 'RELEASED',
    },
    {
      title: 'Parasite',
      description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
      releaseDate: new Date('2019-10-11T00:00:00.000Z'),
      duration: 132,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/...9',
      videoUrl: 'https://www.youtube.com/embed/...9',
      status: 'RELEASED',
    },
    {
      title: 'Gladiator',
      description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
      releaseDate: new Date('2000-05-05T00:00:00.000Z'),
      duration: 155,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/pA3Y5S2g4T8A2s0g51sAPgH2G3.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/0',
      videoUrl: 'https://www.youtube.com/embed/0',
      status: 'RELEASED',
    },
    {
      title: 'Interstellar',
      description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
      releaseDate: new Date('2014-11-07T00:00:00.000Z'),
      duration: 169,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDYtN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/1',
      videoUrl: 'https://www.youtube.com/embed/1',
      status: 'RELEASED',
    },
    {
      title: 'La La Land',
      description: 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
      releaseDate: new Date('2016-12-25T00:00:00.000Z'),
      duration: 128,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/j2MVwDmdVb1275Yy0Bq3o0Ymd0.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/2',
      videoUrl: 'https://www.youtube.com/embed/2',
      status: 'RELEASED',
    },
    {
      title: 'John Wick: Chapter 4',
      description: 'John Wick uncovers a path to defeating the High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
      releaseDate: new Date('2023-03-24T00:00:00.000Z'),
      duration: 169,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/h8gHn0OzBoaefsYseUByqsmEDMY.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/3',
      videoUrl: 'https://www.youtube.com/embed/3',
      status: 'RELEASED',
    },
    {
      title: 'Avatar: The Way of Water',
      description: 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na\'vi race to protect their home.',
      releaseDate: new Date('2022-12-16T00:00:00.000Z'),
      duration: 192,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1MDdnXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/s16H6GraKjcVvSSmHvo9OJo2YAg.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/4',
      videoUrl: 'https://www.youtube.com/embed/4',
      status: 'RELEASED',
    },
    {
      title: 'Get Out',
      description: 'A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.',
      releaseDate: new Date('2017-02-24T00:00:00.000Z'),
      duration: 104,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/8s62i5uYm4Eoj3c6p1a7o31s27p.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/5',
      videoUrl: 'https://www.youtube.com/embed/5',
      status: 'RELEASED',
    },
    {
      title: 'Blade Runner 2049',
      description: 'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who\'s been missing for thirty years.',
      releaseDate: new Date('2017-10-06T00:00:00.000Z'),
      duration: 164,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/gJL5kp7C2bADRMBGlgEpaYdC3zC.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/6',
      videoUrl: 'https://www.youtube.com/embed/6',
      status: 'RELEASED',
    },
    {
      title: 'Mad Max: Fury Road',
      description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the help of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
      releaseDate: new Date('2015-05-15T00:00:00.000Z'),
      duration: 120,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/nlCHUWjY9XWbu2RkCe32SEvaB6g.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/7',
      videoUrl: 'https://www.youtube.com/embed/7',
      status: 'RELEASED',
    },
    {
      title: 'Mai',
      description: 'The life of Mai, a nearly 40-year-old woman, is suddenly turned upside down when she meets Duong. Believing she has found happiness, Mai must face the harsh realities of a society that is not always kind to her.',
      releaseDate: new Date('2024-02-10T00:00:00.000Z'),
      duration: 131,
      posterUrl: 'https://image.tmdb.org/t/p/original/y4M4A293IYgo5n24p79VqjshS9K.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/55pP2f0Nqd9aAbj4UfC6eRzKk2W.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/8',
      videoUrl: 'https://www.youtube.com/embed/8',
      status: 'NOW_SHOWING',
    },
    {
      title: 'The Avengers',
      description: 'Earth\'s mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.',
      releaseDate: new Date('2012-05-04T00:00:00.000Z'),
      duration: 143,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/hbn46fQaRNIkfuRvfAPceoK9eDu.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/9',
      videoUrl: 'https://www.youtube.com/embed/9',
      status: 'RELEASED',
    },
    {
      title: 'Jurassic Park',
      description: 'A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park\'s cloned dinosaurs to run loose.',
      releaseDate: new Date('1993-06-11T00:00:00.000Z'),
      duration: 127,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/5mkLz64aC3Ea1nK1q3G6aYh5x4.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/ABCXYZ1230',
      videoUrl: 'https://www.youtube.com/embed/ABCXYZ1230',
      status: 'RELEASED',
    },
    {
      title: 'Back to the Future',
      description: 'Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.',
      releaseDate: new Date('1985-07-03T00:00:00.000Z'),
      duration: 116,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/fq32r8j4EC0k5V5f42G4wLathJ.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/ABCXYZ1231',
      videoUrl: 'https://www.youtube.com/embed/ABCXYZ1231',
      status: 'RELEASED',
    },
    {
      title: 'The Silence of the Lambs',
      description: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
      releaseDate: new Date('1991-02-14T00:00:00.000Z'),
      duration: 118,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/h7a5c1a9aQp5I2eQcK22m22kY4O.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/ABCXYZ1232',
      videoUrl: 'https://www.youtube.com/embed/ABCXYZ1232',
      status: 'RELEASED',
    },
    {
      title: 'Saving Private Ryan',
      description: 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
      releaseDate: new Date('1998-07-24T00:00:00.000Z'),
      duration: 169,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/2YqugPAx5kH6jJQAa0TAu2s0A5g.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/ABCXYZ1233',
      videoUrl: 'https://www.youtube.com/embed/ABCXYZ1233',
      status: 'RELEASED',
    },
    {
      title: 'Star Wars: Episode IV - A New Hope',
      description: 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire\'s world-destroying battle station, while also attempting to rescue Princess Leia from the evil Darth Vader.',
      releaseDate: new Date('1977-05-25T00:00:00.000Z'),
      duration: 121,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/k6EOrckWCeSGl4c4d22i1eMTiC.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/ABCXYZ1234',
      videoUrl: 'https://www.youtube.com/embed/ABCXYZ1234',
      status: 'RELEASED',
    },
    {
      title: 'The Lord of the Rings: The Fellowship of the Ring',
      description: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
      releaseDate: new Date('2001-12-19T00:00:00.000Z'),
      duration: 178,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/pbrkL804c8yAv3zB5HSp9dKRxJE.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/ABCXYZ1235',
      videoUrl: 'https://www.youtube.com/embed/ABCXYZ1235',
      status: 'RELEASED',
    },
    {
      title: 'Harry Potter and the Sorcerer\'s Stone',
      description: 'An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.',
      releaseDate: new Date('2001-11-16T00:00:00.000Z'),
      duration: 152,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BNmQ0ODBhMjUtNDRhOC00MGQzLTk5MTAtZDliODg5NmU5MjZhXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/hziiv14OpD73u9gAak4XDDpBKa2.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/ABCXYZ1236',
      videoUrl: 'https://www.youtube.com/embed/ABCXYZ1236',
      status: 'RELEASED',
    },
    {
      title: 'Joker',
      description: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.',
      releaseDate: new Date('2019-10-04T00:00:00.000Z'),
      duration: 122,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/ABCXYZ1237',
      videoUrl: 'https://www.youtube.com/embed/ABCXYZ1237',
      status: 'RELEASED',
    },
    {
      title: 'The Lion King',
      description: 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
      releaseDate: new Date('1994-06-24T00:00:00.000Z'),
      duration: 88,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NDI@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/wzE9073LR4kio83JpRamnBqgH2T.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/ABCXYZ1238',
      videoUrl: 'https://www.youtube.com/embed/ABCXYZ1238',
      status: 'RELEASED',
    },
    {
      title: 'Whiplash',
      description: 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
      releaseDate: new Date('2014-10-15T00:00:00.000Z'),
      duration: 106,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/pcjBCi2t2s41T2n5f3gM0g2v3xd.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/ABCXYZ1239',
      videoUrl: 'https://www.youtube.com/embed/ABCXYZ1239',
      status: 'RELEASED',
    },
    {
      title: 'The Departed',
      description: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
      releaseDate: new Date('2006-10-06T00:00:00.000Z'),
      duration: 151,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/fQ401rEVK1nS94b2aYwLq05i1h.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/$0',
      videoUrl: 'https://www.youtube.com/embed/$0',
      status: 'RELEASED',
    },
    {
      title: 'The Prestige',
      description: 'After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
      releaseDate: new Date('2006-10-20T00:00:00.000Z'),
      duration: 130,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/d2J8c9iYkv2B429mzi529n2S0sE.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/$1',
      videoUrl: 'https://www.youtube.com/embed/$1',
      status: 'RELEASED',
    },
    {
      title: 'Alien',
      description: 'The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.',
      releaseDate: new Date('1979-05-25T00:00:00.000Z'),
      duration: 117,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NTE1LWE1NTYtZGQzM2VlZDIyYjU1XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/AmB3pdxI5y693iTfFp2yI1T4pW.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/$2',
      videoUrl: 'https://www.youtube.com/embed/$2',
      status: 'RELEASED',
    },
    {
      title: 'Psycho',
      description: 'A Phoenix secretary embezzles $40,000 from her employer\'s client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.',
      releaseDate: new Date('1960-09-08T00:00:00.000Z'),
      duration: 109,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGU3YjA3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/4gL8gZ105j5yI0Yn227bzgnoSj.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/$3',
      videoUrl: 'https://www.youtube.com/embed/$3',
      status: 'RELEASED',
    },
    {
      title: 'Terminator 2: Judgment Day',
      description: 'A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son, John Connor, from a more advanced and powerful cyborg.',
      releaseDate: new Date('1991-07-03T00:00:00.000Z'),
      duration: 137,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/hlnw9a5tZzV5s4G3gIcgX4p12l.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/$4',
      videoUrl: 'https://www.youtube.com/embed/$4',
      status: 'RELEASED',
    },
    {
      title: 'Mắt Biếc',
      description: 'The unrequited love of a boy for his childhood friend, which spans over several years and through many tribulations.',
      releaseDate: new Date('2019-12-20T00:00:00.000Z'),
      duration: 117,
      posterUrl: 'https://image.tmdb.org/t/p/original/s4iB2i5hGB68s0sV2e62Uu4aD6.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/9JGU7ayGTe12FkM0G5yV2yVdGgW.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/$5',
      videoUrl: 'https://www.youtube.com/embed/$5',
      status: 'RELEASED',
    },
    {
      title: 'The Matrix',
      description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
      releaseDate: new Date('1999-03-31T00:00:00.000Z'),
      duration: 136,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/l4QHerhbt1h8a2m0lHj3n5hdt2.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/$6',
      videoUrl: 'https://www.youtube.com/embed/$6',
      status: 'RELEASED',
    },
    {
      title: 'Goodfellas',
      description: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.',
      releaseDate: new Date('1990-09-19T00:00:00.000Z'),
      duration: 146,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/a4I4p2T4dGz9i1zloYl2n3JPI8i.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/$7',
      videoUrl: 'https://www.youtube.com/embed/$7',
      status: 'RELEASED',
    },
    {
      title: 'One Flew Over the Cuckoo\'s Nest',
      description: 'A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.',
      releaseDate: new Date('1975-11-19T00:00:00.000Z'),
      duration: 133,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BZTE4YTAwOWYtOTY2Ni00YjYyLWE4YjAtZmOTAzNzE5OGVhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/2w4xG123kS8n8QyvAkV441bJ777.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/$8',
      videoUrl: 'https://www.youtube.com/embed/$8',
      status: 'RELEASED',
    },
    {
      title: 'Godzilla Minus One',
      description: 'Post-war Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horrific power of the atomic bomb.',
      releaseDate: new Date('2023-12-01T00:00:00.000Z'),
      duration: 125,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BOTI5ODg1MTgtMmQxYS00YjYxLWEyZDQtYjVlYWMzNGODRlZmXkEyXkFqcGdeQXVyNTY2MjkxODQ@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/nYDPmxvl0if5vHBBp7pDYGkTFc7.jpg'],
      trailerUrl: 'https://www.youtube.com/embed/$9',
      videoUrl: 'https://www.youtube.com/embed/$9',
      status: 'NOW_SHOWING',
    },
    {
      title: 'Spider-Man: Across the Spider-Verse',
      description: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.',
      releaseDate: new Date('2023-06-02T00:00:00.000Z'),
      duration: 140,
      posterUrl: 'https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UX1000_.jpg',
      backdropUrls: ['https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkN4uMhQnuAe.jpg'],
      trailerUrl: 'youtube.com0',
      videoUrl: 'youtube.com0',
      status: 'RELEASED',
    }
  ];

const seedMovies = async () => {
  try {
    await connectDB();
    console.log('Database connected successfully.');

    // await Movie.deleteMany({}); // DO NOT delete old movies
    // console.log('Old movies deleted.');

    for (const movieData of movies_v2) {
      const slug = slugify(movieData.title, { lower: true, strict: true });

      const moviePayload = {
        ...movieData,
        slug,
      };
      
      const query = { slug: moviePayload.slug };
      const options = { upsert: true, new: true, setDefaultsOnInsert: true };

      await Movie.findOneAndUpdate(query, moviePayload, options);
      console.log(`Movie "${movieData.title}" upserted successfully.`);
    }

    console.log('✅ Movie seeding completed successfully!');
  } catch (error) {
    console.error('❌ Error seeding movies:', error);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    console.log('Database connection closed.');
  }
};

seedMovies(); 